server:
  port: ${random.int[10000,19999]}
spring:
  cloud:
    stream:
      bindings:
        stream-kafka-demo-input:
          destination: stream-kafka-topic
          # 实现广播模式，consumer订阅相同的topic创建不同的组
          group: stream-kafka-group02
      default-binder: kafka
  kafka:
    bootstrap-servers: 10.211.55.6:9092
    consumer:
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

