server:
  port: 7888
spring:
  application:
    name: kafka-producer
  cloud:
    stream:
      default:
        binder: kafka
        producer:
          useNativeEncoding: true
        default-binder: kafka
      bindings:
        stream-kafka-output:
          binder: kafka
          # 消息发往的目的地 topic
          destination: stream-kafka-topic
          # 消息发送的格式，接收端不用指定格式，但是发送端要
          content-type: text/plain
          producer:
            use-native-encoding: true
            partitionCount: 5
            configuration:
              key.serializer: org.apache.kafka.common.serialization.StringSerializer
              value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      kafka:
        binder:
          # Kafka的消息中间件服务器
          brokers: 10.211.55.6:9092
          # Zookeeper的节点，如果集群，后面加,号分隔
          zk-nodes: 10.211.55.6:2181
          # 如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
          auto-create-topics: true
  # 开启kafka配置
  kafka:
    enabled: true