server:
  port: 7888
spring:
  application:
    name: kafka-producer
  cloud:
    stream:
      bindings:
        stream-kafka-output:
          destination: stream-kafka-topic
          group: stream-kafka-group
      default-binder: kafka
  kafka:
    bootstrap-servers: 10.211.55.6:9092
    consumer:
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

